# Generated by Django 6.0.5 on 2026-05-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_rename_name_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
