# Generated by Django 6.0.5 on 2026-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=10)),
                ("status", models.IntegerField(default=0)),
                ("max_participants", models.IntegerField(default=100)),
                ("current_participants", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "competition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "audit_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "registration",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
