# Generated by Django 6.0.5 on 2026-05-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_competition_registration_alter_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("change_amount", models.IntegerField(default=0)),
                ("reason", models.CharField(max_length=100)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "point_history",
                "managed": False,
            },
        ),
    ]
