# Generated by Django 6.0.5 on 2026-06-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_point_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.IntegerField()),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                ("audit_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_record",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification",
                "managed": False,
            },
        ),
    ]
